### PR TITLE
WFLY-11566

### PR DESCRIPTION
**Pull request by tadamski**
This change is added in order to allow non-propagating signature for proxy methods which is necessary in: TODO.

### CODE REVIEW

**Comment by tadamski** [comment]
Closing as this would have to wait for WELD-2584.

**Comment by ropalka** [comment]
So is this PR effective or it is closed @tadamski ?

**Comment by tadamski** [comment]
@ropalka I plan to reopen it after WELD-2584 is fixed. The issue can be fixed independently and I wanted to avoid making it convoluted and fix it step by step.

**Comment by manovotn** [comment]
This should probably be closed now as the issue is being solved in another way and the changes caused by carrying generics over to generated classes proved troublesome.
In fact, we should probably also revert the already merged https://github.com/jbossas/jboss-classfilewriter/commit/ea5c534b0edd1c581e1a0106286c18e1f0c5806a. WDYTa @tadamski ?

**Pull request closed without merging**
